[project]
name = "ComfyUI-Block-Space"
version = "1.0.6"
description = "A Figma-style layout and snapping engine for the ComfyUI canvas."
license = "MIT"
repository = "https://github.com/tywoodev/ComfyUI-Block-Space"

[publisher]
name = "ty-woo"

[tool.comfy]
PublisherId = "ty-woo" 
DisplayName = "ComfyUI-Block-Space"
Icon = "https://github.com/tywoodev/ComfyUI-Block-Space/blob/main/assets/logo.svg"